name:                optparse-repl
version:             0.1.0.3
github:              "flipstone/optparse-repl"
license:             MIT
author:              "Flipstone Technology Partners"
maintainer:          "development@flipstone.com"
copyright:           "2023"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/optparse-repl#readme>

tested-with:
    GHC == 8.10.7, GHC == 9.0.2, GHC == 9.2.8, GHC == 9.4.8, GHC == 9.6.7, GHC == 9.8.4, GHC == 9.10.2

dependencies:
- base >= 4.7 && < 5
- isocline >= 1.0 &&  < 1.1
- optparse-applicative >= 0.16 && < 0.19
- safe-exceptions >= 0.1 && < 0.2

flags:
  strict:
    description: More strict ghc options used for development and ci, not intended for end-use.
    manual: true
    default: false

when:
  - condition: flag(strict)
    then:
      ghc-options:
        - -Weverything
        - -Werror
        - -Wno-missing-local-signatures
        - -Wno-monomorphism-restriction
        - -Wno-prepositive-qualified-module
        - -Wno-implicit-prelude
        - -Wno-safe
        - -Wno-unsafe
        - -Wno-missing-safe-haskell-mode
        - -Wno-missing-deriving-strategies
        - -Wno-all-missed-specialisations
        - -Wno-missed-specialisations
      when:
        - condition: impl (ghc >= 9.2)
          ghc-options:
            - -Wno-missing-kind-signatures
        - condition: impl (ghc >= 9.8)
          ghc-options:
            - -Wno-missing-role-annotations
            - -Wno-missing-poly-kind-signatures
        - condition: impl (ghc >= 9.10)
          ghc-options:
            - -Wno-defaulted-exception-context
    else:
      ghc-options:
        - -Wall

library:
  source-dirs: src
  exposed-modules:
    - Options.Applicative.Repl

